### ISSUE TITLE
Missing category attribute on result 

### ISSUE THREAD

**Issue by matseriksen** [strapi/strapi-starter-nuxt-blog#20]
I get this Error where the keys in apollo doesnt match the keys in the returned object. 

`Missing category attribute on result {
  articles: [
    {
      id: '1',
      title: 'Test',
      content: 'Content',
      image: [Object],
      category: [Object],
      __typename: 'Article'
    }
  ]
}`

Everything works just fine, just an annoying error message in the console.

**Comment by markkaylor** [comment]
Can you share the apollo query? How are you using apollo, @nuxtjs/apollo? or something else?
This might be helpful https://github.com/vuejs/vue-apollo/issues/700

**Comment by markkaylor** [comment]
Hello @matseriksen !

As we have not received any new or updated information in over 14 days we are marking this issue/discussion as closed. Should you have new information please feel free to respond and we can consider reopening it.

For others finding this closed issue and you have updated information, please open up a new bug report and simply reference this closed bug report so that we can get any new information you may have. If you have questions please refer to the [contributor's guide](https://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue) on opening issues.

Thank you and have a great day!
